# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe6314995fedc8390f7547ec0819c5721f63795f801898749927b9955b83345fba4c19de4e692d96b75fa61974cf58626b35d100a1281194d12abc4906e71bc8

test:
  secret_key_base: 1b3addd13a4d8eabd30e023dcdf87b51cb9d520694e837a4176f762a78801bbe0301bdc23c9acc58cf70ebfdeec49950bf9e1f6bfe750458f5c5d07152eab2cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
